setup_params:
  computer_id: 15
  run_id: 4
  fitness_weights: (-1.0, -1.0)
  use_neat: False
  max_ind_length: 30
  gate_set: ["h", "x", "mcx", "rx", "ry", "rz", "swap", "mcp"]
  max_time: 15
  min_gate_error: 0.05
  test_problem: qft
  simulator_type: "statevector"
  verbose: False

hyper_params:
  cross_prob: 0.8
  mut_prob: 0.35
  pop_size: 500
  num_elites: 25

base_gp_params:
  min_ind_length: 3
  insert_gate_prob: 0
  insert_gate_sequence_prob: 0.1
  insert_gate_sequence_and_inverse_prob: 0.08
  delete_gate_sequence_prob: 0.2
  move_gate_sequence_prob: 0.07
  swap_gates_prob: 0.05
  substitute_gate_prob: 0.1
  change_angle_prob: 0.28
  change_qubits_prob: 0.12
